# Configuration file for a web server
# Inspired by NGINX server configuration

server:
  listen: 80
  server_name: example.com
  client_error_page: 4xx.html
  server_error_page: 5xx.html
  client_max_body_size: 1024
  root: /var/www/html
  location: /
    allow_methods: GET, POST, DELETE
    root: /var/www/html
    autoindex: on
  location: /redirect
    return: 301 https://example.com
  location: ~ \.php$
    fastcgi_pass:

server:
  listen: 8080
  server_name: example2.com
  client_error_page: 4xx.html
  server_error_page: 5xx.html
  client_max_body_size: 1024
  root: /var/www/html
  location: /
    allow_methods: GET, POST, DELETE
    root: /var/www/html
    autoindex: on
  location: /redirect
    return: 301 https://example2.com
  location: ~ \.php$
    fastcgi_pass: