server:
  listen: 10028
  server_name: www.example.com
  error_page: error.html
  client_max_body_size: 0
  root: /resources
  location: /
    allow_methods: GET
    index: index.html
    autoindex: on
  location: /guide
    allow_methods: GET
    index: html_guide.html
    autoindex: on
  location: /exam
    allow_methods: GET
    index: html_exam.html
    autoindex: off
  location: /banana
    allow_methods: GET
    index: banana.html
    autoindex: on
  location: /upload
    allow_methods: GET POST
    index: upload.html
    autoindex: off
  location: /delete
    allow_methods: GET POST DELETE
    index: delete.html
    autoindex: off

server:
  listen: 10029
  server_name: www.example.org
  error_page: error.html
  client_max_body_size: 0
  root: /resources
  location: /
    allow_methods: GET
    index: index.html
    autoindex: on
  location: /guide
    allow_methods: GET
    index: html_guide.html
    autoindex: on
  location: /exam
    allow_methods: GET
    index: html_exam.html
    autoindex: off
  location: /banana
    allow_methods: GET
    index: banana.html
    autoindex: on
  location: /upload
    allow_methods: GET POST
    index: upload.html
    autoindex: off
  location: /delete
    allow_methods: GET POST DELETE
    index: delete.html
    autoindex: off