server:
  listen: 80
  server_name: example1.com
  error_page: error.html
  index: index.html
  client_max_body_size: 1024
  root: /Users/gimgibeom/webserv
  location: /
    allow_methods: GET POST DELETE
    root: /Users/gimgibeom/webserv
    index: index.html
    autoindex: on
  location: /resources
    allow_methods: GET POST DELETE
    root: /Users/gimgibeom/webserv
    index: index.html
    autoindex: on
  location: /redirect
    return: 301 https://example.com
  location: ~ \.php$
    fastcgi_pass:
    
server:
  listen: 8080
  server_name: example2.com
  error_page: error.html
  index: index.html
  client_max_body_size: 1024
  root: /Users/gimgibeom/webserv
  location: /
    allow_methods: GET POST DELETE
    root: /Users/gimgibeom/webserv
    index: index.html
    autoindex: on
  location: /resources/
    allow_methods: GET POST DELETE
    root: /Users/gimgibeom/webserv
    index: index.html
    autoindex: on
  location: /redirect
    return: 301 https://example.com
  location: ~ \.php$
    fastcgi_pass: