server:
  listen: 8080
  server_name: www.42seoul.org
  error_page: error.html
  index: index.html
  client_max_body_size: 1024
  root: resources
  location: /guide
    allow_methods: GET
    index: index.html
    autoindex: off
  location: /exam
    allow_methods: POST
    index: index.html
    autoindex: on