server:
  listen: 10028
  server_name: yaggoman.com:10028
  error_page: error.html
  client_max_body_size: 3
  root: /resources
  location: /
    allow_methods: GET
    index: index.html
    autoindex: off
    client_max_body_size: 3
    error_page: error.html
  location: /guide
    allow_methods: GET
    index: html_guide.html
    autoindex: off
  location: /exam
    allow_methods: GET
    index: html_exam.html
    autoindex: off
  location: /banana
    allow_methods: GET
    index: banana.html
    autoindex: off
  location: /upload
    allow_methods: GET POST DELETE
    index: cgi_post.html
    autoindex: off
  location: /cgi-bin
    allow_methods: GET POST
    index: current_time.py
    cgi_path: /usr/local/bin/python3
    autoindex: off

server:
  listen: 10029
  server_name: yaggoman.com:10029
  error_page: error.html
  client_max_body_size: 3
  root: /resources
  location: /
    allow_methods: GET
    autoindex: on
    client_max_body_size: 3
    error_page: error.html
  location: /guide
    allow_methods: GET
    autoindex: on
  location: /exam
    allow_methods: GET
    autoindex: on
  location: /banana
    allow_methods: GET
    autoindex: on
  location: /upload
    allow_methods: GET POST DELETE
    autoindex: on
  location: /cgi-bin
    allow_methods: GET POST
    cgi_path: /usr/local/bin/python3
    autoindex: on
